#!/usr/bin/env python3
"""Pull per-country visitor counts from GoatCounter into _data/visitor_stats.yml.

The site map at /visitors/ renders whatever this script writes, so swapping the
analytics backend later only means rewriting fetch_locations().

Credentials come from the environment, never from this file:

    GOATCOUNTER_CODE    your site code, i.e. the <code> in <code>.goatcounter.com
    GOATCOUNTER_TOKEN   an API token from Settings -> API tokens (needs "read statistics")

Usage:
    python scripts/update_visitor_stats.py            # all time
    python scripts/update_visitor_stats.py --start 2026-01-01
"""
import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

API_PAGE_SIZE = 100
TIMEOUT = 30


def fetch_locations(code, token, start=None, end=None):
    """Return [(country_code, display_name, visitors), ...] sorted high to low."""
    url = f"https://{code}.goatcounter.com/api/v0/stats/locations"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    rows, offset = [], 0
    while True:
        params = {"limit": API_PAGE_SIZE, "offset": offset}
        if start:
            params["start"] = start
        if end:
            params["end"] = end

        resp = requests.get(url, params=params, headers=headers, timeout=TIMEOUT)
        if resp.status_code != 200:
            sys.exit(f"GoatCounter API returned {resp.status_code}: {resp.text[:300]}")

        payload = resp.json()
        batch = payload.get("stats", [])
        rows.extend(batch)

        if not payload.get("more") or not batch:
            break
        offset += len(batch)

    out = []
    for item in rows:
        cc = (item.get("id") or "").strip().upper()
        count = int(item.get("count") or 0)
        # GoatCounter reports unresolved IPs with an empty id
        if not cc or count <= 0:
            continue
        out.append((cc, item.get("name") or cc, count))

    out.sort(key=lambda r: (-r[2], r[0]))
    return out


def yaml_quote(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(rows, period):
    total = sum(r[2] for r in rows)
    lines = [
        "# Generated by scripts/update_visitor_stats.py -- do not edit by hand.",
        f"updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"period: {yaml_quote(period)}",
        f"total_visitors: {total}",
        f"country_count: {len(rows)}",
        "countries:",
    ]
    for cc, name, count in rows:
        lines.append(f"  - code: {yaml_quote(cc)}")
        lines.append(f"    name: {yaml_quote(name)}")
        lines.append(f"    visitors: {count}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--start", help="start date, YYYY-MM-DD (default: all time)")
    ap.add_argument("--end", help="end date, YYYY-MM-DD")
    ap.add_argument("--out", default="_data/visitor_stats.yml")
    args = ap.parse_args()

    code = os.environ.get("GOATCOUNTER_CODE")
    token = os.environ.get("GOATCOUNTER_TOKEN")
    if not code or not token:
        sys.exit(
            "Set GOATCOUNTER_CODE and GOATCOUNTER_TOKEN in the environment.\n"
            "  PowerShell:  $env:GOATCOUNTER_CODE='yourcode'; $env:GOATCOUNTER_TOKEN='...'\n"
            "  bash:        export GOATCOUNTER_CODE=yourcode GOATCOUNTER_TOKEN=..."
        )

    rows = fetch_locations(code, token, args.start, args.end)
    period = f"{args.start or 'all time'}" + (f" to {args.end}" if args.end else "")
    text = render(rows, period)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    old = out_path.read_text(encoding="utf-8") if out_path.exists() else ""

    # ignore the timestamp line when deciding whether anything really changed
    def body(t):
        return "\n".join(l for l in t.splitlines() if not l.startswith("updated:"))

    if body(text) == body(old):
        print(f"No change ({len(rows)} countries, {sum(r[2] for r in rows)} visitors).")
        return

    out_path.write_text(text, encoding="utf-8")
    print(f"Wrote {out_path}: {len(rows)} countries, {sum(r[2] for r in rows)} visitors.")


if __name__ == "__main__":
    main()
